# Copyright 2026 The Buildish Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Provider-neutral authored release policy blocks."""

from __future__ import annotations

import re
from string import Formatter
from typing import Annotated, Literal

from pydantic import Field, field_validator, model_validator

from buildish_release_tooling.docs.documentation import ComponentOwnedAuthoredModel

_CANDIDATE_LABEL_PATTERN = re.compile(r"[a-z][a-z0-9-]*")


class ComponentIdentityConfig(ComponentOwnedAuthoredModel):
    """Stable machine and human identities for one released component."""

    id: str = Field(description="Stable machine identifier used in release state and manifests.")
    display_name: str = Field(description="Human-facing component name used in release text.")

    @field_validator("id", "display_name")
    @classmethod
    def _validate_non_empty(cls, value: str) -> str:
        normalized = value.strip()
        if not normalized:
            raise ValueError("component identities must not be empty")
        return normalized


class VersioningConfig(ComponentOwnedAuthoredModel):
    """Version syntax and immutable final-tag naming policy."""

    scheme: Literal["semver"] = Field(
        default="semver",
        description="Version syntax used by release state derivation.",
    )
    final_tag_template: str = Field(
        default="v{version}",
        description="Template used to derive the immutable final tag from a version.",
    )

    @field_validator("final_tag_template")
    @classmethod
    def _validate_final_tag_template(cls, value: str) -> str:
        if value.count("{version}") != 1:
            raise ValueError("final_tag_template must contain {version} exactly once")
        return value


class PlatformGeneratedSourceSnapshotConfig(ComponentOwnedAuthoredModel):
    """Policy that relies on source snapshots generated by the hosting platform."""

    mode: Literal["platform-generated"] = Field(
        default="platform-generated",
        description="Source snapshot policy discriminator.",
    )


class BuiltSourceSnapshotConfig(ComponentOwnedAuthoredModel):
    """Policy for a separately built source archive release asset."""

    mode: Literal["built-asset"] = Field(
        default="built-asset",
        description="Source snapshot policy discriminator.",
    )
    filename_template: str = Field(
        description="Template used to name the built source archive.",
    )
    archive_root_template: str = Field(
        description="Template used for the archive's top-level directory.",
    )

    @field_validator("filename_template", "archive_root_template")
    @classmethod
    def _validate_versioned_template(cls, value: str) -> str:
        if "{version}" not in value:
            raise ValueError("built source snapshot templates must contain {version}")
        field_names = {
            field_name
            for _literal, field_name, _format_spec, _conversion in Formatter().parse(value)
            if field_name is not None
        }
        if not field_names.issubset({"component", "version"}):
            raise ValueError(
                "built source snapshot templates may use only {component} and {version}"
            )
        return value


class NoSourceSnapshotConfig(ComponentOwnedAuthoredModel):
    """Policy for a release that intentionally publishes no source snapshot."""

    mode: Literal["none"] = Field(
        default="none",
        description="Source snapshot policy discriminator.",
    )


SourceSnapshotConfig = Annotated[
    PlatformGeneratedSourceSnapshotConfig
    | BuiltSourceSnapshotConfig
    | NoSourceSnapshotConfig,
    Field(discriminator="mode"),
]


class SourceChecksConfig(ComponentOwnedAuthoredModel):
    """Checks required for an exact source revision before artifact production."""

    run_selected_ref_tests: bool = Field(
        default=False,
        description="Whether the candidate preparation flow runs component tests itself.",
    )
    require_release_branch_ci: bool = Field(
        default=False,
        description="Whether a green release-branch CI result is required.",
    )

    @model_validator(mode="after")
    def _validate_at_least_one_check(self) -> SourceChecksConfig:
        if not self.run_selected_ref_tests and not self.require_release_branch_ci:
            raise ValueError(
                "source checks must run selected-ref tests or require release-branch CI"
            )
        return self


class SourceConfig(ComponentOwnedAuthoredModel):
    """Source-selection, source-check, and snapshot policy."""

    selection: Literal[
        "explicit-ref-or-default-branch",
        "explicit-ref",
        "release-branch",
    ] = Field(description="Policy used to resolve the exact release source revision.")
    default_branch: str | None = Field(
        default=None,
        description="Optional default branch used when source selection permits it.",
    )
    snapshot: SourceSnapshotConfig = Field(
        description="Policy for source material exposed to release consumers.",
    )
    checks: SourceChecksConfig = Field(
        default_factory=SourceChecksConfig,
        description="Checks required for the selected source revision.",
    )

    @model_validator(mode="after")
    def _validate_default_branch(self) -> SourceConfig:
        if self.selection == "explicit-ref-or-default-branch" and not self.default_branch:
            raise ValueError(
                "source.default_branch is required for explicit-ref-or-default-branch selection"
            )
        return self


class DirectLifecycleConfig(ComponentOwnedAuthoredModel):
    """Release lifecycle that publishes a final release without a candidate."""

    mode: Literal["direct"] = Field(
        default="direct",
        description="Release lifecycle discriminator.",
    )


class CandidateLifecycleConfig(ComponentOwnedAuthoredModel):
    """Release lifecycle that creates candidates and promotes one exact candidate."""

    mode: Literal["candidate"] = Field(
        default="candidate",
        description="Release lifecycle discriminator.",
    )


LifecycleConfig = Annotated[
    DirectLifecycleConfig | CandidateLifecycleConfig,
    Field(discriminator="mode"),
]


class CandidateConfig(ComponentOwnedAuthoredModel):
    """Candidate numbering, visibility, and retention policy."""

    label: str = Field(
        default="rc",
        description="Lowercase label placed before the numeric candidate suffix.",
    )
    start_number: int = Field(
        default=1,
        ge=0,
        description="First candidate number when no matching candidate tag exists.",
    )
    visibility: Literal["draft", "public-prerelease"] = Field(
        default="public-prerelease",
        description="Requested visibility after candidate publication is verified.",
    )
    retention: Literal["retain-published", "retain-all"] = Field(
        default="retain-published",
        description="Retention policy for earlier candidate publications.",
    )

    @field_validator("label")
    @classmethod
    def _validate_label(cls, value: str) -> str:
        normalized = value.strip().lower()
        if _CANDIDATE_LABEL_PATTERN.fullmatch(normalized) is None:
            raise ValueError("candidate.label must match [a-z][a-z0-9-]*")
        return normalized


class ArtifactPolicyConfig(ComponentOwnedAuthoredModel):
    """Produced artifact families and integrity sidecar policy."""

    produced: list[str] = Field(
        default_factory=list,
        description="Artifact families produced by component-owned build jobs.",
    )
    checksums: list[Literal["sha256", "sha512"]] = Field(
        default_factory=list,
        description="Checksums required for produced file artifacts.",
    )


class TagPolicyConfig(ComponentOwnedAuthoredModel):
    """Immutable-tag materialization and optional moving-tag policy."""

    final_mode: Literal["exact-source-commit", "detached-materialization-commit"] = Field(
        default="exact-source-commit",
        description="Commit policy used for the immutable final tag.",
    )
    moving: list[str] = Field(
        default_factory=list,
        description="Explicit moving tag or alias policies enabled for the component.",
    )
    include_final_mode_in_summary: bool = Field(
        default=False,
        description="Whether summaries render the selected final-tag materialization mode.",
    )


class GenericVoteMaterialsConfig(ComponentOwnedAuthoredModel):
    """Project-neutral vote-material rendering policy."""

    profile: Literal["generic"] = Field(
        default="generic",
        description="Vote-material profile discriminator.",
    )
    release_name: str = Field(description="Human-facing name rendered in vote materials.")
    verification_guide_url: str = Field(
        description="User-facing release verification guide URL.",
    )
    instructions: str = Field(
        description="Human-facing verification instructions for the exact candidate.",
    )
