# Copyright 2026 The Buildish Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""GitHub Release title and body rendering."""

from __future__ import annotations

from buildish_release_tooling.release.contracts import (
    IncubatorDisclaimer,
    RcVoteManifestV1,
)
from buildish_release_tooling.release.config import (
    ReleaseConfig,
    require_asf_profile,
    require_vote_materials,
)
from buildish_release_tooling.release.core.state import (
    CandidateReleaseState,
    DirectReleaseState,
    PromotionState,
)
from buildish_release_tooling.release.core.models import ArtifactReference
from buildish_release_tooling.release.release_text import (
    incubator_disclaimer_section,
)


def _append_optional_section(lines: list[str], section: str) -> None:
    if not section:
        return
    lines.extend(["", section])


def render_direct_final_release_body(
    state: DirectReleaseState | PromotionState,
) -> str:
    """Render deterministic GitHub release text for a direct final release."""

    lines = [
        f"{state.release.component.display_name} {state.release.version}",
        "",
        "## Release identity",
        "",
        f"Final tag: {state.final_tag.name}",
        f"Source commit: {state.source.commit_sha}",
    ]
    if isinstance(state, PromotionState):
        lines.extend(
            [
                f"Promoted candidate: {state.candidate.tag.name}",
                f"Candidate manifest SHA-256: {state.candidate_manifest_digest}",
            ]
        )
    if state.artifacts:
        lines.extend(
            [
                "",
                "## Release assets",
                "",
                *[f"- {artifact.logical_name}" for artifact in state.artifacts],
            ]
        )
    else:
        lines.extend(
            [
                "",
                "Source archives are generated by GitHub from the immutable final tag.",
            ]
        )
    return "\n".join(lines)


def render_candidate_release_body(
    state: CandidateReleaseState,
    artifacts: list[ArtifactReference],
) -> str:
    """Render deterministic GitHub release text for one exact candidate."""

    lines = [
        f"{state.release.component.display_name} {state.release.version} candidate",
        "",
        "## Candidate identity",
        "",
        f"Candidate tag: {state.candidate.tag.name}",
        f"Source commit: {state.source.commit_sha}",
    ]
    if artifacts:
        lines.extend(
            [
                "",
                "## Candidate assets",
                "",
                *[f"- {artifact.logical_name}" for artifact in artifacts],
            ]
        )
    else:
        lines.extend(
            [
                "",
                "Source archives are generated by GitHub from the immutable candidate tag.",
            ]
        )
    return "\n".join(lines)


def _draft_metadata_lines(
    component_config: ReleaseConfig, state: CandidateReleaseState
) -> list[str]:
    return [
        f"Candidate tag: {state.rc_tag}",
        f"Final tag: {state.final_tag}",
        f"Resolved source ref: {state.resolved_source_ref}",
        f"ASF SVN staging URL: {state.candidate_publication_uri}",
        f"Final tag mode: {component_config.tags.final_mode}",
    ]


def _release_url(component_config: ReleaseConfig, version: str) -> str:
    return f"{require_asf_profile(component_config).dist_release_base.rstrip('/')}/{version}/"


def _source_release_lines(
    component_config: ReleaseConfig, version: str, vote_manifest: RcVoteManifestV1
) -> list[str]:
    source_artifact = vote_manifest.vote_materials.source_artifacts[0]
    source_url = f"{_release_url(component_config, version)}{source_artifact.filename}"
    return [
        "Source artifact:",
        f"- {source_url}",
        f"- {source_url}.sha512",
        f"- {source_url}.asc",
    ]


def render_draft_github_release_body(
    component_config: ReleaseConfig,
    *,
    state: CandidateReleaseState,
    incubator_disclaimer: IncubatorDisclaimer | None,
    candidate_visibility: str = "draft",
) -> str:
    """Render the initial candidate GitHub Release body."""

    lines = [
        f"Candidate GitHub Release placeholder for {component_config.component.display_name} {state.final_tag.removeprefix('v')}.",
    ]
    _append_optional_section(
        lines,
        incubator_disclaimer_section(
            incubator_disclaimer, heading="## Incubating Disclaimer"
        ),
    )
    lines.extend(
        [
            "",
            *_draft_metadata_lines(component_config, state),
            "",
        ]
    )
    if candidate_visibility == "draft":
        lines.append(
            "This draft release is convenience metadata only and must remain unpublished until the ASF vote passes."
        )
    elif candidate_visibility == "public-prerelease":
        lines.append(
            "This public candidate GitHub Release is convenience metadata only. "
            "It is not an official ASF release and must be marked as a GitHub pre-release."
        )
    else:
        raise ValueError(f"unsupported candidate visibility: {candidate_visibility}")
    return "\n".join(lines)


def render_final_github_release_body(
    component_config: ReleaseConfig,
    *,
    version: str,
    vote_manifest: RcVoteManifestV1,
) -> str:
    """Render the public GitHub Release body for a finalized release."""

    lines = [
        f"{component_config.component.display_name} {version}",
    ]
    _append_optional_section(
        lines,
        incubator_disclaimer_section(
            vote_manifest.incubator_disclaimer,
            heading="## Incubating Disclaimer",
        ),
    )
    lines.extend(
        [
            "",
            "Candidate tag:",
            f"- {vote_manifest.rc_tag}",
            "",
            "## Authoritative Source Release",
            "",
            "The authoritative ASF source release is available from:",
            f"- {_release_url(component_config, version)}",
            "",
            *_source_release_lines(component_config, version, vote_manifest),
            "",
            "KEYS:",
            f"- {require_asf_profile(component_config).keys_url}",
            "",
            "Release verification guide:",
            f"- {require_vote_materials(component_config).verification_guide_url}",
            "",
            "## GitHub Release",
            "",
            (
                "This GitHub Release is provided as convenience metadata only. "
                "GitHub release assets are convenience artifacts and are not the authoritative ASF release."
            ),
        ]
    )
    return "\n".join(lines)


def render_finalized_draft_github_release_body(
    component_config: ReleaseConfig,
    *,
    state: CandidateReleaseState,
    incubator_disclaimer: IncubatorDisclaimer | None,
    authoritative_manifest_url: str,
    bootstrap_script_url: str,
    bootstrap_invoker: str,
) -> str:
    """Render the draft GitHub Release body after RC vote materials exist."""

    lines = [
        f"Candidate GitHub Release placeholder for {component_config.component.display_name} {state.final_tag.removeprefix('v')}.",
    ]
    _append_optional_section(
        lines,
        incubator_disclaimer_section(
            incubator_disclaimer, heading="## Incubating Disclaimer"
        ),
    )
    lines.extend(
        [
            "",
            *_draft_metadata_lines(component_config, state),
            "",
            "Authoritative RC vote manifest:",
            f"- {authoritative_manifest_url}",
            f"- {authoritative_manifest_url}.sha512",
            f"- {authoritative_manifest_url}.asc",
            "",
            "Verification bootstrap convenience:",
            f"- {bootstrap_script_url}",
            f"- {bootstrap_script_url}.sha512",
            f"- {bootstrap_script_url}.asc",
            "",
            "Verify RC bootstrap one-liner:",
            "",
            "```sh",
            bootstrap_invoker,
            "```",
            "",
            "This draft release is convenience metadata only and must remain unpublished until the ASF vote passes.",
        ]
    )
    return "\n".join(lines)
